/* main_window.c generated by valac 0.48.14, the Vala compiler
 * generated from main_window.vala, do not modify */

/* main_window.vala
 *
 * Copyright 2021 Benjamin Quinn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#define REPOSE_WIDGETS_TYPE_MAIN_WINDOW (repose_widgets_main_window_get_type ())
#define REPOSE_WIDGETS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_WIDGETS_TYPE_MAIN_WINDOW, ReposeWidgetsMainWindow))
#define REPOSE_WIDGETS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_WIDGETS_TYPE_MAIN_WINDOW, ReposeWidgetsMainWindowClass))
#define REPOSE_WIDGETS_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_WIDGETS_TYPE_MAIN_WINDOW))
#define REPOSE_WIDGETS_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_WIDGETS_TYPE_MAIN_WINDOW))
#define REPOSE_WIDGETS_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_WIDGETS_TYPE_MAIN_WINDOW, ReposeWidgetsMainWindowClass))

typedef struct _ReposeWidgetsMainWindow ReposeWidgetsMainWindow;
typedef struct _ReposeWidgetsMainWindowClass ReposeWidgetsMainWindowClass;
typedef struct _ReposeWidgetsMainWindowPrivate ReposeWidgetsMainWindowPrivate;

#define REPOSE_MODELS_TYPE_ROOT_STATE (repose_models_root_state_get_type ())
#define REPOSE_MODELS_ROOT_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootState))
#define REPOSE_MODELS_ROOT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootStateClass))
#define REPOSE_MODELS_IS_ROOT_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_MODELS_TYPE_ROOT_STATE))
#define REPOSE_MODELS_IS_ROOT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_MODELS_TYPE_ROOT_STATE))
#define REPOSE_MODELS_ROOT_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootStateClass))

typedef struct _ReposeModelsRootState ReposeModelsRootState;
typedef struct _ReposeModelsRootStateClass ReposeModelsRootStateClass;
enum  {
	REPOSE_WIDGETS_MAIN_WINDOW_0_PROPERTY,
	REPOSE_WIDGETS_MAIN_WINDOW_NUM_PROPERTIES
};
static GParamSpec* repose_widgets_main_window_properties[REPOSE_WIDGETS_MAIN_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define REPOSE_MODELS_TYPE_REQUEST (repose_models_request_get_type ())
#define REPOSE_MODELS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest))
#define REPOSE_MODELS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))
#define REPOSE_MODELS_IS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_IS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))

typedef struct _ReposeModelsRequest ReposeModelsRequest;
typedef struct _ReposeModelsRequestClass ReposeModelsRequestClass;

#define REPOSE_WIDGETS_TYPE_REQUEST_EDITOR (repose_widgets_request_editor_get_type ())
#define REPOSE_WIDGETS_REQUEST_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditor))
#define REPOSE_WIDGETS_REQUEST_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditorClass))
#define REPOSE_WIDGETS_IS_REQUEST_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR))
#define REPOSE_WIDGETS_IS_REQUEST_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR))
#define REPOSE_WIDGETS_REQUEST_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditorClass))

typedef struct _ReposeWidgetsRequestEditor ReposeWidgetsRequestEditor;
typedef struct _ReposeWidgetsRequestEditorClass ReposeWidgetsRequestEditorClass;

struct _ReposeWidgetsMainWindow {
	GtkWindow parent_instance;
	ReposeWidgetsMainWindowPrivate * priv;
};

struct _ReposeWidgetsMainWindowClass {
	GtkWindowClass parent_class;
};

struct _ReposeWidgetsMainWindowPrivate {
	GtkNotebook* active_requests_notebook;
	ReposeModelsRootState* root_state;
};

static gint ReposeWidgetsMainWindow_private_offset;
static gpointer repose_widgets_main_window_parent_class = NULL;

GType repose_widgets_main_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeWidgetsMainWindow, g_object_unref)
GType repose_models_root_state_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeModelsRootState, g_object_unref)
ReposeWidgetsMainWindow* repose_widgets_main_window_new (GtkApplication* app);
ReposeWidgetsMainWindow* repose_widgets_main_window_construct (GType object_type,
                                                               GtkApplication* app);
ReposeModelsRootState* repose_models_root_state_new (void);
ReposeModelsRootState* repose_models_root_state_construct (GType object_type);
static void __lambda5_ (ReposeWidgetsMainWindow* self,
                 GObject* s,
                 GParamSpec* p);
static void ___lambda5__g_object_notify (GObject* _sender,
                                  GParamSpec* pspec,
                                  gpointer self);
ReposeModelsRequest* repose_models_request_new (const gchar* name,
                                                const gchar* url,
                                                const gchar* method);
ReposeModelsRequest* repose_models_request_construct (GType object_type,
                                                      const gchar* name,
                                                      const gchar* url,
                                                      const gchar* method);
GType repose_models_request_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeModelsRequest, g_object_unref)
void repose_models_root_state_set_active_request (ReposeModelsRootState* self,
                                                  ReposeModelsRequest* value);
ReposeWidgetsRequestEditor* repose_widgets_request_editor_new (void);
ReposeWidgetsRequestEditor* repose_widgets_request_editor_construct (GType object_type);
GType repose_widgets_request_editor_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeWidgetsRequestEditor, g_object_unref)
static void repose_widgets_main_window_on_new_request_button_clicked (ReposeWidgetsMainWindow* self,
                                                               GtkButton* btn);
static void _repose_widgets_main_window_on_new_request_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                                   gpointer self);
static void repose_widgets_main_window_finalize (GObject * obj);
static GType repose_widgets_main_window_get_type_once (void);

static inline gpointer
repose_widgets_main_window_get_instance_private (ReposeWidgetsMainWindow* self)
{
	return G_STRUCT_MEMBER_P (self, ReposeWidgetsMainWindow_private_offset);
}

static void
__lambda5_ (ReposeWidgetsMainWindow* self,
            GObject* s,
            GParamSpec* p)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
#line 37 "../src/widgets/main_window.vala"
	g_return_if_fail (s != NULL);
#line 37 "../src/widgets/main_window.vala"
	g_return_if_fail (p != NULL);
#line 38 "../src/widgets/main_window.vala"
	_tmp0_ = g_type_name (G_TYPE_FROM_INSTANCE (s));
#line 38 "../src/widgets/main_window.vala"
	_tmp1_ = g_param_spec_get_name (p);
#line 38 "../src/widgets/main_window.vala"
	g_info ("main_window.vala:38: %s - %s", _tmp0_, _tmp1_);
#line 153 "main_window.c"
}

static void
___lambda5__g_object_notify (GObject* _sender,
                             GParamSpec* pspec,
                             gpointer self)
{
#line 37 "../src/widgets/main_window.vala"
	__lambda5_ ((ReposeWidgetsMainWindow*) self, _sender, pspec);
#line 163 "main_window.c"
}

ReposeWidgetsMainWindow*
repose_widgets_main_window_construct (GType object_type,
                                      GtkApplication* app)
{
	ReposeWidgetsMainWindow * self = NULL;
	ReposeModelsRootState* _tmp0_;
	ReposeModelsRootState* _tmp1_;
	ReposeModelsRootState* _tmp2_;
	ReposeModelsRequest* _tmp3_;
	ReposeModelsRequest* _tmp4_;
	GtkNotebook* _tmp5_;
	ReposeWidgetsRequestEditor* _tmp6_;
	ReposeWidgetsRequestEditor* _tmp7_;
	GtkLabel* _tmp8_;
	GtkLabel* _tmp9_;
#line 31 "../src/widgets/main_window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 32 "../src/widgets/main_window.vala"
	self = (ReposeWidgetsMainWindow*) g_object_new (object_type, "application", app, NULL);
#line 34 "../src/widgets/main_window.vala"
	_tmp0_ = repose_models_root_state_new ();
#line 34 "../src/widgets/main_window.vala"
	_g_object_unref0 (self->priv->root_state);
#line 34 "../src/widgets/main_window.vala"
	self->priv->root_state = _tmp0_;
#line 36 "../src/widgets/main_window.vala"
	g_info ("main_window.vala:36: Hello logging");
#line 37 "../src/widgets/main_window.vala"
	_tmp1_ = self->priv->root_state;
#line 37 "../src/widgets/main_window.vala"
	g_signal_connect_object ((GObject*) _tmp1_, "notify", (GCallback) ___lambda5__g_object_notify, self, 0);
#line 40 "../src/widgets/main_window.vala"
	_tmp2_ = self->priv->root_state;
#line 40 "../src/widgets/main_window.vala"
	_tmp3_ = repose_models_request_new ("", "", "");
#line 40 "../src/widgets/main_window.vala"
	_tmp4_ = _tmp3_;
#line 40 "../src/widgets/main_window.vala"
	repose_models_root_state_set_active_request (_tmp2_, _tmp4_);
#line 40 "../src/widgets/main_window.vala"
	_g_object_unref0 (_tmp4_);
#line 42 "../src/widgets/main_window.vala"
	_tmp5_ = self->priv->active_requests_notebook;
#line 42 "../src/widgets/main_window.vala"
	_tmp6_ = repose_widgets_request_editor_new ();
#line 42 "../src/widgets/main_window.vala"
	g_object_ref_sink (_tmp6_);
#line 42 "../src/widgets/main_window.vala"
	_tmp7_ = _tmp6_;
#line 42 "../src/widgets/main_window.vala"
	_tmp8_ = (GtkLabel*) gtk_label_new ("New Request");
#line 42 "../src/widgets/main_window.vala"
	g_object_ref_sink (_tmp8_);
#line 42 "../src/widgets/main_window.vala"
	_tmp9_ = _tmp8_;
#line 42 "../src/widgets/main_window.vala"
	gtk_notebook_append_page (_tmp5_, (GtkWidget*) _tmp7_, (GtkWidget*) _tmp9_);
#line 42 "../src/widgets/main_window.vala"
	_g_object_unref0 (_tmp9_);
#line 42 "../src/widgets/main_window.vala"
	_g_object_unref0 (_tmp7_);
#line 31 "../src/widgets/main_window.vala"
	return self;
#line 229 "main_window.c"
}

ReposeWidgetsMainWindow*
repose_widgets_main_window_new (GtkApplication* app)
{
#line 31 "../src/widgets/main_window.vala"
	return repose_widgets_main_window_construct (REPOSE_WIDGETS_TYPE_MAIN_WINDOW, app);
#line 237 "main_window.c"
}

static void
repose_widgets_main_window_on_new_request_button_clicked (ReposeWidgetsMainWindow* self,
                                                          GtkButton* btn)
{
	GtkNotebook* _tmp0_;
	ReposeWidgetsRequestEditor* _tmp1_;
	ReposeWidgetsRequestEditor* _tmp2_;
	GtkLabel* _tmp3_;
	GtkLabel* _tmp4_;
#line 46 "../src/widgets/main_window.vala"
	g_return_if_fail (self != NULL);
#line 46 "../src/widgets/main_window.vala"
	g_return_if_fail (btn != NULL);
#line 47 "../src/widgets/main_window.vala"
	_tmp0_ = self->priv->active_requests_notebook;
#line 47 "../src/widgets/main_window.vala"
	_tmp1_ = repose_widgets_request_editor_new ();
#line 47 "../src/widgets/main_window.vala"
	g_object_ref_sink (_tmp1_);
#line 47 "../src/widgets/main_window.vala"
	_tmp2_ = _tmp1_;
#line 47 "../src/widgets/main_window.vala"
	_tmp3_ = (GtkLabel*) gtk_label_new ("New Request");
#line 47 "../src/widgets/main_window.vala"
	g_object_ref_sink (_tmp3_);
#line 47 "../src/widgets/main_window.vala"
	_tmp4_ = _tmp3_;
#line 47 "../src/widgets/main_window.vala"
	gtk_notebook_append_page (_tmp0_, (GtkWidget*) _tmp2_, (GtkWidget*) _tmp4_);
#line 47 "../src/widgets/main_window.vala"
	_g_object_unref0 (_tmp4_);
#line 47 "../src/widgets/main_window.vala"
	_g_object_unref0 (_tmp2_);
#line 273 "main_window.c"
}

static void
_repose_widgets_main_window_on_new_request_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                              gpointer self)
{
#line 21 "../src/widgets/main_window.vala"
	repose_widgets_main_window_on_new_request_button_clicked ((ReposeWidgetsMainWindow*) self, _sender);
#line 282 "main_window.c"
}

static void
repose_widgets_main_window_class_init (ReposeWidgetsMainWindowClass * klass,
                                       gpointer klass_data)
{
#line 21 "../src/widgets/main_window.vala"
	repose_widgets_main_window_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/widgets/main_window.vala"
	g_type_class_adjust_private_offset (klass, &ReposeWidgetsMainWindow_private_offset);
#line 21 "../src/widgets/main_window.vala"
	G_OBJECT_CLASS (klass)->finalize = repose_widgets_main_window_finalize;
#line 21 "../src/widgets/main_window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/me/blq/Repose/ui/MainWindow.ui");
#line 21 "../src/widgets/main_window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "active_requests_notebook", FALSE, ReposeWidgetsMainWindow_private_offset + G_STRUCT_OFFSET (ReposeWidgetsMainWindowPrivate, active_requests_notebook));
#line 21 "../src/widgets/main_window.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_new_request_button_clicked", G_CALLBACK(_repose_widgets_main_window_on_new_request_button_clicked_gtk_button_clicked));
#line 301 "main_window.c"
}

static void
repose_widgets_main_window_instance_init (ReposeWidgetsMainWindow * self,
                                          gpointer klass)
{
#line 21 "../src/widgets/main_window.vala"
	self->priv = repose_widgets_main_window_get_instance_private (self);
#line 21 "../src/widgets/main_window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 312 "main_window.c"
}

static void
repose_widgets_main_window_finalize (GObject * obj)
{
	ReposeWidgetsMainWindow * self;
#line 21 "../src/widgets/main_window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPOSE_WIDGETS_TYPE_MAIN_WINDOW, ReposeWidgetsMainWindow);
#line 25 "../src/widgets/main_window.vala"
	_g_object_unref0 (self->priv->active_requests_notebook);
#line 29 "../src/widgets/main_window.vala"
	_g_object_unref0 (self->priv->root_state);
#line 21 "../src/widgets/main_window.vala"
	G_OBJECT_CLASS (repose_widgets_main_window_parent_class)->finalize (obj);
#line 327 "main_window.c"
}

static GType
repose_widgets_main_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReposeWidgetsMainWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repose_widgets_main_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReposeWidgetsMainWindow), 0, (GInstanceInitFunc) repose_widgets_main_window_instance_init, NULL };
	GType repose_widgets_main_window_type_id;
	repose_widgets_main_window_type_id = g_type_register_static (gtk_window_get_type (), "ReposeWidgetsMainWindow", &g_define_type_info, 0);
	ReposeWidgetsMainWindow_private_offset = g_type_add_instance_private (repose_widgets_main_window_type_id, sizeof (ReposeWidgetsMainWindowPrivate));
	return repose_widgets_main_window_type_id;
}

GType
repose_widgets_main_window_get_type (void)
{
	static volatile gsize repose_widgets_main_window_type_id__volatile = 0;
	if (g_once_init_enter (&repose_widgets_main_window_type_id__volatile)) {
		GType repose_widgets_main_window_type_id;
		repose_widgets_main_window_type_id = repose_widgets_main_window_get_type_once ();
		g_once_init_leave (&repose_widgets_main_window_type_id__volatile, repose_widgets_main_window_type_id);
	}
	return repose_widgets_main_window_type_id__volatile;
}

