/* request_editor.c generated by valac 0.48.14, the Vala compiler
 * generated from request_editor.vala, do not modify */

/* request_editor.vala
 *
 * Copyright 2021 Benjamin Quinn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>

#define REPOSE_WIDGETS_TYPE_REQUEST_EDITOR (repose_widgets_request_editor_get_type ())
#define REPOSE_WIDGETS_REQUEST_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditor))
#define REPOSE_WIDGETS_REQUEST_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditorClass))
#define REPOSE_WIDGETS_IS_REQUEST_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR))
#define REPOSE_WIDGETS_IS_REQUEST_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR))
#define REPOSE_WIDGETS_REQUEST_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_WIDGETS_TYPE_REQUEST_EDITOR, ReposeWidgetsRequestEditorClass))

typedef struct _ReposeWidgetsRequestEditor ReposeWidgetsRequestEditor;
typedef struct _ReposeWidgetsRequestEditorClass ReposeWidgetsRequestEditorClass;
typedef struct _ReposeWidgetsRequestEditorPrivate ReposeWidgetsRequestEditorPrivate;
enum  {
	REPOSE_WIDGETS_REQUEST_EDITOR_0_PROPERTY,
	REPOSE_WIDGETS_REQUEST_EDITOR_NUM_PROPERTIES
};
static GParamSpec* repose_widgets_request_editor_properties[REPOSE_WIDGETS_REQUEST_EDITOR_NUM_PROPERTIES];

struct _ReposeWidgetsRequestEditor {
	GtkBox parent_instance;
	ReposeWidgetsRequestEditorPrivate * priv;
};

struct _ReposeWidgetsRequestEditorClass {
	GtkBoxClass parent_class;
};

static gpointer repose_widgets_request_editor_parent_class = NULL;

GType repose_widgets_request_editor_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeWidgetsRequestEditor, g_object_unref)
ReposeWidgetsRequestEditor* repose_widgets_request_editor_new (void);
ReposeWidgetsRequestEditor* repose_widgets_request_editor_construct (GType object_type);
static void repose_widgets_request_editor_on_save_pressed (ReposeWidgetsRequestEditor* self,
                                                    GtkButton* btn);
static void _repose_widgets_request_editor_on_save_pressed_gtk_button_clicked (GtkButton* _sender,
                                                                        gpointer self);
static void repose_widgets_request_editor_on_send_pressed (ReposeWidgetsRequestEditor* self,
                                                    GtkButton* btn);
static void _repose_widgets_request_editor_on_send_pressed_gtk_button_clicked (GtkButton* _sender,
                                                                        gpointer self);
static void repose_widgets_request_editor_on_request_name_changed (ReposeWidgetsRequestEditor* self);
static void _repose_widgets_request_editor_on_request_name_changed_gtk_editable_changed (GtkEditable* _sender,
                                                                                  gpointer self);
static GType repose_widgets_request_editor_get_type_once (void);

ReposeWidgetsRequestEditor*
repose_widgets_request_editor_construct (GType object_type)
{
	ReposeWidgetsRequestEditor * self = NULL;
#line 22 "../src/widgets/request_editor.vala"
	self = (ReposeWidgetsRequestEditor*) g_object_new (object_type, NULL);
#line 22 "../src/widgets/request_editor.vala"
	return self;
#line 79 "request_editor.c"
}

ReposeWidgetsRequestEditor*
repose_widgets_request_editor_new (void)
{
#line 22 "../src/widgets/request_editor.vala"
	return repose_widgets_request_editor_construct (REPOSE_WIDGETS_TYPE_REQUEST_EDITOR);
#line 87 "request_editor.c"
}

static void
repose_widgets_request_editor_on_save_pressed (ReposeWidgetsRequestEditor* self,
                                               GtkButton* btn)
{
#line 26 "../src/widgets/request_editor.vala"
	g_return_if_fail (self != NULL);
#line 26 "../src/widgets/request_editor.vala"
	g_return_if_fail (btn != NULL);
#line 98 "request_editor.c"
}

static void
_repose_widgets_request_editor_on_save_pressed_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self)
{
#line 21 "../src/widgets/request_editor.vala"
	repose_widgets_request_editor_on_save_pressed ((ReposeWidgetsRequestEditor*) self, _sender);
#line 107 "request_editor.c"
}

static void
repose_widgets_request_editor_on_send_pressed (ReposeWidgetsRequestEditor* self,
                                               GtkButton* btn)
{
#line 29 "../src/widgets/request_editor.vala"
	g_return_if_fail (self != NULL);
#line 29 "../src/widgets/request_editor.vala"
	g_return_if_fail (btn != NULL);
#line 118 "request_editor.c"
}

static void
_repose_widgets_request_editor_on_send_pressed_gtk_button_clicked (GtkButton* _sender,
                                                                   gpointer self)
{
#line 21 "../src/widgets/request_editor.vala"
	repose_widgets_request_editor_on_send_pressed ((ReposeWidgetsRequestEditor*) self, _sender);
#line 127 "request_editor.c"
}

static void
repose_widgets_request_editor_on_request_name_changed (ReposeWidgetsRequestEditor* self)
{
#line 32 "../src/widgets/request_editor.vala"
	g_return_if_fail (self != NULL);
#line 135 "request_editor.c"
}

static void
_repose_widgets_request_editor_on_request_name_changed_gtk_editable_changed (GtkEditable* _sender,
                                                                             gpointer self)
{
#line 21 "../src/widgets/request_editor.vala"
	repose_widgets_request_editor_on_request_name_changed ((ReposeWidgetsRequestEditor*) self);
#line 144 "request_editor.c"
}

static void
repose_widgets_request_editor_class_init (ReposeWidgetsRequestEditorClass * klass,
                                          gpointer klass_data)
{
#line 21 "../src/widgets/request_editor.vala"
	repose_widgets_request_editor_parent_class = g_type_class_peek_parent (klass);
#line 21 "../src/widgets/request_editor.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/me/blq/Repose/ui/RequestEditor.ui");
#line 21 "../src/widgets/request_editor.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_save_pressed", G_CALLBACK(_repose_widgets_request_editor_on_save_pressed_gtk_button_clicked));
#line 21 "../src/widgets/request_editor.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_send_pressed", G_CALLBACK(_repose_widgets_request_editor_on_send_pressed_gtk_button_clicked));
#line 21 "../src/widgets/request_editor.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_request_name_changed", G_CALLBACK(_repose_widgets_request_editor_on_request_name_changed_gtk_editable_changed));
#line 161 "request_editor.c"
}

static void
repose_widgets_request_editor_instance_init (ReposeWidgetsRequestEditor * self,
                                             gpointer klass)
{
#line 21 "../src/widgets/request_editor.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 170 "request_editor.c"
}

static GType
repose_widgets_request_editor_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReposeWidgetsRequestEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repose_widgets_request_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReposeWidgetsRequestEditor), 0, (GInstanceInitFunc) repose_widgets_request_editor_instance_init, NULL };
	GType repose_widgets_request_editor_type_id;
	repose_widgets_request_editor_type_id = g_type_register_static (gtk_box_get_type (), "ReposeWidgetsRequestEditor", &g_define_type_info, 0);
	return repose_widgets_request_editor_type_id;
}

GType
repose_widgets_request_editor_get_type (void)
{
	static volatile gsize repose_widgets_request_editor_type_id__volatile = 0;
	if (g_once_init_enter (&repose_widgets_request_editor_type_id__volatile)) {
		GType repose_widgets_request_editor_type_id;
		repose_widgets_request_editor_type_id = repose_widgets_request_editor_get_type_once ();
		g_once_init_leave (&repose_widgets_request_editor_type_id__volatile, repose_widgets_request_editor_type_id);
	}
	return repose_widgets_request_editor_type_id__volatile;
}

