/* window.c generated by valac 0.48.14, the Vala compiler
 * generated from window.vala, do not modify */

/* window.vala
 *
 * Copyright 2021 Benjamin Quinn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <gtk/gtk.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <libsoup/soup.h>
#include <json-glib/json-glib.h>

#define REPOSE_TYPE_WINDOW (repose_window_get_type ())
#define REPOSE_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_TYPE_WINDOW, ReposeWindow))
#define REPOSE_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_TYPE_WINDOW, ReposeWindowClass))
#define REPOSE_IS_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_TYPE_WINDOW))
#define REPOSE_IS_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_TYPE_WINDOW))
#define REPOSE_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_TYPE_WINDOW, ReposeWindowClass))

typedef struct _ReposeWindow ReposeWindow;
typedef struct _ReposeWindowClass ReposeWindowClass;
typedef struct _ReposeWindowPrivate ReposeWindowPrivate;
enum  {
	REPOSE_WINDOW_0_PROPERTY,
	REPOSE_WINDOW_NUM_PROPERTIES
};
static GParamSpec* repose_window_properties[REPOSE_WINDOW_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _ReposeWindow {
	GtkWindow parent_instance;
	ReposeWindowPrivate * priv;
};

struct _ReposeWindowClass {
	GtkWindowClass parent_class;
};

struct _ReposeWindowPrivate {
	GtkStack* response_stack;
	GtkSpinner* loading_spinner;
	GtkScrolledWindow* response_text_scroll;
	GtkTextView* response_text;
};

static gint ReposeWindow_private_offset;
static gpointer repose_window_parent_class = NULL;

GType repose_window_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeWindow, g_object_unref)
ReposeWindow* repose_window_new (GtkApplication* app);
ReposeWindow* repose_window_construct (GType object_type,
                                       GtkApplication* app);
static void repose_window_on_new_request_button_clicked (ReposeWindow* self,
                                                  GtkButton* btn);
static void __lambda5_ (ReposeWindow* self,
                 SoupSession* sess,
                 SoupMessage* msg);
static void ___lambda5__soup_session_callback (SoupSession* session,
                                        SoupMessage* msg,
                                        gpointer self);
static void _repose_window_on_new_request_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                      gpointer self);
static void repose_window_finalize (GObject * obj);
static GType repose_window_get_type_once (void);

static inline gpointer
repose_window_get_instance_private (ReposeWindow* self)
{
	return G_STRUCT_MEMBER_P (self, ReposeWindow_private_offset);
}

ReposeWindow*
repose_window_construct (GType object_type,
                         GtkApplication* app)
{
	ReposeWindow * self = NULL;
#line 34 "../src/window.vala"
	g_return_val_if_fail (app != NULL, NULL);
#line 35 "../src/window.vala"
	self = (ReposeWindow*) g_object_new (object_type, "application", app, NULL);
#line 34 "../src/window.vala"
	return self;
#line 104 "window.c"
}

ReposeWindow*
repose_window_new (GtkApplication* app)
{
#line 34 "../src/window.vala"
	return repose_window_construct (REPOSE_TYPE_WINDOW, app);
#line 112 "window.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 51 "../src/window.vala"
	return self ? g_object_ref (self) : NULL;
#line 120 "window.c"
}

static void
__lambda5_ (ReposeWindow* self,
            SoupSession* sess,
            SoupMessage* msg)
{
	GtkStack* _tmp0_;
	GtkScrolledWindow* _tmp1_;
	GtkSpinner* _tmp2_;
	GError* _inner_error0_ = NULL;
#line 51 "../src/window.vala"
	g_return_if_fail (sess != NULL);
#line 51 "../src/window.vala"
	g_return_if_fail (msg != NULL);
#line 52 "../src/window.vala"
	_tmp0_ = self->priv->response_stack;
#line 52 "../src/window.vala"
	_tmp1_ = self->priv->response_text_scroll;
#line 52 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp0_, (GtkWidget*) _tmp1_);
#line 53 "../src/window.vala"
	_tmp2_ = self->priv->loading_spinner;
#line 53 "../src/window.vala"
	g_object_set (_tmp2_, "active", FALSE, NULL);
#line 146 "window.c"
	{
		JsonParser* parser = NULL;
		JsonParser* _tmp3_;
		SoupMessageBody* _tmp4_;
		guint8* _tmp5_;
		gint _tmp5__length1;
		JsonGenerator* generator = NULL;
		JsonGenerator* _tmp6_;
		JsonGenerator* _tmp7_;
		JsonNode* _tmp8_;
		JsonGenerator* _tmp9_;
		JsonGenerator* _tmp10_;
		gchar* pretty_json = NULL;
		JsonGenerator* _tmp11_;
		gchar* _tmp12_;
		GtkTextView* _tmp13_;
		GtkTextBuffer* _tmp14_;
		const gchar* _tmp15_;
#line 56 "../src/window.vala"
		_tmp3_ = json_parser_new ();
#line 56 "../src/window.vala"
		parser = _tmp3_;
#line 57 "../src/window.vala"
		_tmp4_ = msg->response_body;
#line 57 "../src/window.vala"
		_tmp5_ = _tmp4_->data;
#line 57 "../src/window.vala"
		_tmp5__length1 = _tmp4_->length;
#line 57 "../src/window.vala"
		json_parser_load_from_data (parser, (const gchar*) _tmp5_, (gssize) -1, &_inner_error0_);
#line 57 "../src/window.vala"
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 57 "../src/window.vala"
			_g_object_unref0 (parser);
#line 181 "window.c"
			goto __catch0_g_error;
		}
#line 59 "../src/window.vala"
		_tmp6_ = json_generator_new ();
#line 59 "../src/window.vala"
		generator = _tmp6_;
#line 60 "../src/window.vala"
		_tmp7_ = generator;
#line 60 "../src/window.vala"
		_tmp8_ = json_parser_get_root (parser);
#line 60 "../src/window.vala"
		json_generator_set_root (_tmp7_, _tmp8_);
#line 61 "../src/window.vala"
		_tmp9_ = generator;
#line 61 "../src/window.vala"
		json_generator_set_pretty (_tmp9_, TRUE);
#line 62 "../src/window.vala"
		_tmp10_ = generator;
#line 62 "../src/window.vala"
		json_generator_set_indent (_tmp10_, (guint) 4);
#line 64 "../src/window.vala"
		_tmp11_ = generator;
#line 64 "../src/window.vala"
		_tmp12_ = json_generator_to_data (_tmp11_, NULL);
#line 64 "../src/window.vala"
		pretty_json = _tmp12_;
#line 66 "../src/window.vala"
		_tmp13_ = self->priv->response_text;
#line 66 "../src/window.vala"
		_tmp14_ = gtk_text_view_get_buffer (_tmp13_);
#line 66 "../src/window.vala"
		_tmp15_ = pretty_json;
#line 66 "../src/window.vala"
		gtk_text_buffer_set_text (_tmp14_, _tmp15_, -1);
#line 55 "../src/window.vala"
		_g_free0 (pretty_json);
#line 55 "../src/window.vala"
		_g_object_unref0 (generator);
#line 55 "../src/window.vala"
		_g_object_unref0 (parser);
#line 222 "window.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		GtkTextView* _tmp16_;
		GtkTextBuffer* _tmp17_;
		GError* _tmp18_;
		const gchar* _tmp19_;
		gchar* _tmp20_;
		gchar* _tmp21_;
#line 55 "../src/window.vala"
		e = _inner_error0_;
#line 55 "../src/window.vala"
		_inner_error0_ = NULL;
#line 68 "../src/window.vala"
		_tmp16_ = self->priv->response_text;
#line 68 "../src/window.vala"
		_tmp17_ = gtk_text_view_get_buffer (_tmp16_);
#line 68 "../src/window.vala"
		_tmp18_ = e;
#line 68 "../src/window.vala"
		_tmp19_ = _tmp18_->message;
#line 68 "../src/window.vala"
		_tmp20_ = g_strdup_printf ("Something went wrong: %s", _tmp19_);
#line 68 "../src/window.vala"
		_tmp21_ = _tmp20_;
#line 68 "../src/window.vala"
		gtk_text_buffer_set_text (_tmp17_, _tmp21_, -1);
#line 68 "../src/window.vala"
		_g_free0 (_tmp21_);
#line 55 "../src/window.vala"
		_g_error_free0 (e);
#line 256 "window.c"
	}
	__finally0:
#line 55 "../src/window.vala"
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
#line 55 "../src/window.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
#line 55 "../src/window.vala"
		g_clear_error (&_inner_error0_);
#line 55 "../src/window.vala"
		return;
#line 267 "window.c"
	}
}

static void
___lambda5__soup_session_callback (SoupSession* session,
                                   SoupMessage* msg,
                                   gpointer self)
{
#line 51 "../src/window.vala"
	__lambda5_ ((ReposeWindow*) self, session, msg);
#line 51 "../src/window.vala"
	g_object_unref (self);
#line 280 "window.c"
}

static void
repose_window_on_new_request_button_clicked (ReposeWindow* self,
                                             GtkButton* btn)
{
	gchar* url = NULL;
	gchar* _tmp0_;
	SoupSession* session = NULL;
	SoupSession* _tmp1_;
	SoupMessage* message = NULL;
	SoupMessage* _tmp2_;
	GtkSpinner* _tmp3_;
	GtkStack* _tmp4_;
	GtkSpinner* _tmp5_;
	SoupMessage* _tmp6_;
#line 39 "../src/window.vala"
	g_return_if_fail (self != NULL);
#line 39 "../src/window.vala"
	g_return_if_fail (btn != NULL);
#line 41 "../src/window.vala"
	_tmp0_ = g_strdup ("https://jsonplaceholder.typicode.com/comments");
#line 41 "../src/window.vala"
	url = _tmp0_;
#line 44 "../src/window.vala"
	_tmp1_ = soup_session_new ();
#line 44 "../src/window.vala"
	session = _tmp1_;
#line 45 "../src/window.vala"
	_tmp2_ = soup_message_new ("GET", url);
#line 45 "../src/window.vala"
	message = _tmp2_;
#line 47 "../src/window.vala"
	_tmp3_ = self->priv->loading_spinner;
#line 47 "../src/window.vala"
	g_object_set (_tmp3_, "active", TRUE, NULL);
#line 48 "../src/window.vala"
	_tmp4_ = self->priv->response_stack;
#line 48 "../src/window.vala"
	_tmp5_ = self->priv->loading_spinner;
#line 48 "../src/window.vala"
	gtk_stack_set_visible_child (_tmp4_, (GtkWidget*) _tmp5_);
#line 51 "../src/window.vala"
	_tmp6_ = _g_object_ref0 (message);
#line 51 "../src/window.vala"
	soup_session_queue_message (session, _tmp6_, ___lambda5__soup_session_callback, g_object_ref (self));
#line 39 "../src/window.vala"
	_g_object_unref0 (message);
#line 39 "../src/window.vala"
	_g_object_unref0 (session);
#line 39 "../src/window.vala"
	_g_free0 (url);
#line 333 "window.c"
}

static void
_repose_window_on_new_request_button_clicked_gtk_button_clicked (GtkButton* _sender,
                                                                 gpointer self)
{
#line 25 "../src/window.vala"
	repose_window_on_new_request_button_clicked ((ReposeWindow*) self, _sender);
#line 342 "window.c"
}

static void
repose_window_class_init (ReposeWindowClass * klass,
                          gpointer klass_data)
{
#line 25 "../src/window.vala"
	repose_window_parent_class = g_type_class_peek_parent (klass);
#line 25 "../src/window.vala"
	g_type_class_adjust_private_offset (klass, &ReposeWindow_private_offset);
#line 25 "../src/window.vala"
	G_OBJECT_CLASS (klass)->finalize = repose_window_finalize;
#line 25 "../src/window.vala"
	gtk_widget_class_set_template_from_resource (GTK_WIDGET_CLASS (klass), "/me/blq/Repose/window.ui");
#line 25 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "response_stack", FALSE, ReposeWindow_private_offset + G_STRUCT_OFFSET (ReposeWindowPrivate, response_stack));
#line 25 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "loading_spinner", FALSE, ReposeWindow_private_offset + G_STRUCT_OFFSET (ReposeWindowPrivate, loading_spinner));
#line 25 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "response_text_scroll", FALSE, ReposeWindow_private_offset + G_STRUCT_OFFSET (ReposeWindowPrivate, response_text_scroll));
#line 25 "../src/window.vala"
	gtk_widget_class_bind_template_child_full (GTK_WIDGET_CLASS (klass), "response_text", FALSE, ReposeWindow_private_offset + G_STRUCT_OFFSET (ReposeWindowPrivate, response_text));
#line 25 "../src/window.vala"
	gtk_widget_class_bind_template_callback_full (GTK_WIDGET_CLASS (klass), "on_new_request_button_clicked", G_CALLBACK(_repose_window_on_new_request_button_clicked_gtk_button_clicked));
#line 367 "window.c"
}

static void
repose_window_instance_init (ReposeWindow * self,
                             gpointer klass)
{
#line 25 "../src/window.vala"
	self->priv = repose_window_get_instance_private (self);
#line 25 "../src/window.vala"
	gtk_widget_init_template (GTK_WIDGET (self));
#line 378 "window.c"
}

static void
repose_window_finalize (GObject * obj)
{
	ReposeWindow * self;
#line 25 "../src/window.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPOSE_TYPE_WINDOW, ReposeWindow);
#line 26 "../src/window.vala"
	_g_object_unref0 (self->priv->response_stack);
#line 28 "../src/window.vala"
	_g_object_unref0 (self->priv->loading_spinner);
#line 30 "../src/window.vala"
	_g_object_unref0 (self->priv->response_text_scroll);
#line 32 "../src/window.vala"
	_g_object_unref0 (self->priv->response_text);
#line 25 "../src/window.vala"
	G_OBJECT_CLASS (repose_window_parent_class)->finalize (obj);
#line 397 "window.c"
}

static GType
repose_window_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReposeWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repose_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReposeWindow), 0, (GInstanceInitFunc) repose_window_instance_init, NULL };
	GType repose_window_type_id;
	repose_window_type_id = g_type_register_static (gtk_window_get_type (), "ReposeWindow", &g_define_type_info, 0);
	ReposeWindow_private_offset = g_type_add_instance_private (repose_window_type_id, sizeof (ReposeWindowPrivate));
	return repose_window_type_id;
}

GType
repose_window_get_type (void)
{
	static volatile gsize repose_window_type_id__volatile = 0;
	if (g_once_init_enter (&repose_window_type_id__volatile)) {
		GType repose_window_type_id;
		repose_window_type_id = repose_window_get_type_once ();
		g_once_init_leave (&repose_window_type_id__volatile, repose_window_type_id);
	}
	return repose_window_type_id__volatile;
}

