/* request.c generated by valac 0.48.14, the Vala compiler
 * generated from request.vala, do not modify */

/* request.vala
 *
 * Copyright 2021 Benjamin Quinn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define REPOSE_MODELS_TYPE_REQUEST (repose_models_request_get_type ())
#define REPOSE_MODELS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest))
#define REPOSE_MODELS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))
#define REPOSE_MODELS_IS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_IS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))

typedef struct _ReposeModelsRequest ReposeModelsRequest;
typedef struct _ReposeModelsRequestClass ReposeModelsRequestClass;
typedef struct _ReposeModelsRequestPrivate ReposeModelsRequestPrivate;
enum  {
	REPOSE_MODELS_REQUEST_0_PROPERTY,
	REPOSE_MODELS_REQUEST_NAME_PROPERTY,
	REPOSE_MODELS_REQUEST_URL_PROPERTY,
	REPOSE_MODELS_REQUEST_METHOD_PROPERTY,
	REPOSE_MODELS_REQUEST_NUM_PROPERTIES
};
static GParamSpec* repose_models_request_properties[REPOSE_MODELS_REQUEST_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ReposeModelsRequest {
	GObject parent_instance;
	ReposeModelsRequestPrivate * priv;
};

struct _ReposeModelsRequestClass {
	GObjectClass parent_class;
};

struct _ReposeModelsRequestPrivate {
	gchar* _name;
	gchar* _url;
	gchar* _method;
};

static gint ReposeModelsRequest_private_offset;
static gpointer repose_models_request_parent_class = NULL;

GType repose_models_request_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeModelsRequest, g_object_unref)
ReposeModelsRequest* repose_models_request_new (const gchar* name,
                                                const gchar* url,
                                                const gchar* method);
ReposeModelsRequest* repose_models_request_construct (GType object_type,
                                                      const gchar* name,
                                                      const gchar* url,
                                                      const gchar* method);
void repose_models_request_set_name (ReposeModelsRequest* self,
                                     const gchar* value);
void repose_models_request_set_url (ReposeModelsRequest* self,
                                    const gchar* value);
void repose_models_request_set_method (ReposeModelsRequest* self,
                                       const gchar* value);
const gchar* repose_models_request_get_name (ReposeModelsRequest* self);
const gchar* repose_models_request_get_url (ReposeModelsRequest* self);
const gchar* repose_models_request_get_method (ReposeModelsRequest* self);
static void repose_models_request_finalize (GObject * obj);
static GType repose_models_request_get_type_once (void);
static void _vala_repose_models_request_get_property (GObject * object,
                                               guint property_id,
                                               GValue * value,
                                               GParamSpec * pspec);
static void _vala_repose_models_request_set_property (GObject * object,
                                               guint property_id,
                                               const GValue * value,
                                               GParamSpec * pspec);

static inline gpointer
repose_models_request_get_instance_private (ReposeModelsRequest* self)
{
	return G_STRUCT_MEMBER_P (self, ReposeModelsRequest_private_offset);
}

ReposeModelsRequest*
repose_models_request_construct (GType object_type,
                                 const gchar* name,
                                 const gchar* url,
                                 const gchar* method)
{
	ReposeModelsRequest * self = NULL;
#line 25 "../src/model/request.vala"
	g_return_val_if_fail (name != NULL, NULL);
#line 25 "../src/model/request.vala"
	g_return_val_if_fail (url != NULL, NULL);
#line 25 "../src/model/request.vala"
	g_return_val_if_fail (method != NULL, NULL);
#line 25 "../src/model/request.vala"
	self = (ReposeModelsRequest*) g_object_new (object_type, NULL);
#line 26 "../src/model/request.vala"
	repose_models_request_set_name (self, name);
#line 27 "../src/model/request.vala"
	repose_models_request_set_url (self, url);
#line 28 "../src/model/request.vala"
	repose_models_request_set_method (self, method);
#line 25 "../src/model/request.vala"
	return self;
#line 124 "request.c"
}

ReposeModelsRequest*
repose_models_request_new (const gchar* name,
                           const gchar* url,
                           const gchar* method)
{
#line 25 "../src/model/request.vala"
	return repose_models_request_construct (REPOSE_MODELS_TYPE_REQUEST, name, url, method);
#line 134 "request.c"
}

const gchar*
repose_models_request_get_name (ReposeModelsRequest* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 21 "../src/model/request.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "../src/model/request.vala"
	_tmp0_ = self->priv->_name;
#line 21 "../src/model/request.vala"
	result = _tmp0_;
#line 21 "../src/model/request.vala"
	return result;
#line 150 "request.c"
}

void
repose_models_request_set_name (ReposeModelsRequest* self,
                                const gchar* value)
{
	gchar* old_value;
#line 21 "../src/model/request.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/model/request.vala"
	old_value = repose_models_request_get_name (self);
#line 21 "../src/model/request.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 164 "request.c"
		gchar* _tmp0_;
#line 21 "../src/model/request.vala"
		_tmp0_ = g_strdup (value);
#line 21 "../src/model/request.vala"
		_g_free0 (self->priv->_name);
#line 21 "../src/model/request.vala"
		self->priv->_name = _tmp0_;
#line 21 "../src/model/request.vala"
		g_object_notify_by_pspec ((GObject *) self, repose_models_request_properties[REPOSE_MODELS_REQUEST_NAME_PROPERTY]);
#line 174 "request.c"
	}
}

const gchar*
repose_models_request_get_url (ReposeModelsRequest* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 22 "../src/model/request.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/model/request.vala"
	_tmp0_ = self->priv->_url;
#line 22 "../src/model/request.vala"
	result = _tmp0_;
#line 22 "../src/model/request.vala"
	return result;
#line 191 "request.c"
}

void
repose_models_request_set_url (ReposeModelsRequest* self,
                               const gchar* value)
{
	gchar* old_value;
#line 22 "../src/model/request.vala"
	g_return_if_fail (self != NULL);
#line 22 "../src/model/request.vala"
	old_value = repose_models_request_get_url (self);
#line 22 "../src/model/request.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 205 "request.c"
		gchar* _tmp0_;
#line 22 "../src/model/request.vala"
		_tmp0_ = g_strdup (value);
#line 22 "../src/model/request.vala"
		_g_free0 (self->priv->_url);
#line 22 "../src/model/request.vala"
		self->priv->_url = _tmp0_;
#line 22 "../src/model/request.vala"
		g_object_notify_by_pspec ((GObject *) self, repose_models_request_properties[REPOSE_MODELS_REQUEST_URL_PROPERTY]);
#line 215 "request.c"
	}
}

const gchar*
repose_models_request_get_method (ReposeModelsRequest* self)
{
	const gchar* result;
	const gchar* _tmp0_;
#line 23 "../src/model/request.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 23 "../src/model/request.vala"
	_tmp0_ = self->priv->_method;
#line 23 "../src/model/request.vala"
	result = _tmp0_;
#line 23 "../src/model/request.vala"
	return result;
#line 232 "request.c"
}

void
repose_models_request_set_method (ReposeModelsRequest* self,
                                  const gchar* value)
{
	gchar* old_value;
#line 23 "../src/model/request.vala"
	g_return_if_fail (self != NULL);
#line 23 "../src/model/request.vala"
	old_value = repose_models_request_get_method (self);
#line 23 "../src/model/request.vala"
	if (g_strcmp0 (value, old_value) != 0) {
#line 246 "request.c"
		gchar* _tmp0_;
#line 23 "../src/model/request.vala"
		_tmp0_ = g_strdup (value);
#line 23 "../src/model/request.vala"
		_g_free0 (self->priv->_method);
#line 23 "../src/model/request.vala"
		self->priv->_method = _tmp0_;
#line 23 "../src/model/request.vala"
		g_object_notify_by_pspec ((GObject *) self, repose_models_request_properties[REPOSE_MODELS_REQUEST_METHOD_PROPERTY]);
#line 256 "request.c"
	}
}

static void
repose_models_request_class_init (ReposeModelsRequestClass * klass,
                                  gpointer klass_data)
{
#line 20 "../src/model/request.vala"
	repose_models_request_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/model/request.vala"
	g_type_class_adjust_private_offset (klass, &ReposeModelsRequest_private_offset);
#line 20 "../src/model/request.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_repose_models_request_get_property;
#line 20 "../src/model/request.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_repose_models_request_set_property;
#line 20 "../src/model/request.vala"
	G_OBJECT_CLASS (klass)->finalize = repose_models_request_finalize;
#line 20 "../src/model/request.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPOSE_MODELS_REQUEST_NAME_PROPERTY, repose_models_request_properties[REPOSE_MODELS_REQUEST_NAME_PROPERTY] = g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 20 "../src/model/request.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPOSE_MODELS_REQUEST_URL_PROPERTY, repose_models_request_properties[REPOSE_MODELS_REQUEST_URL_PROPERTY] = g_param_spec_string ("url", "url", "url", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 20 "../src/model/request.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPOSE_MODELS_REQUEST_METHOD_PROPERTY, repose_models_request_properties[REPOSE_MODELS_REQUEST_METHOD_PROPERTY] = g_param_spec_string ("method", "method", "method", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 280 "request.c"
}

static void
repose_models_request_instance_init (ReposeModelsRequest * self,
                                     gpointer klass)
{
#line 20 "../src/model/request.vala"
	self->priv = repose_models_request_get_instance_private (self);
#line 289 "request.c"
}

static void
repose_models_request_finalize (GObject * obj)
{
	ReposeModelsRequest * self;
#line 20 "../src/model/request.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest);
#line 21 "../src/model/request.vala"
	_g_free0 (self->priv->_name);
#line 22 "../src/model/request.vala"
	_g_free0 (self->priv->_url);
#line 23 "../src/model/request.vala"
	_g_free0 (self->priv->_method);
#line 20 "../src/model/request.vala"
	G_OBJECT_CLASS (repose_models_request_parent_class)->finalize (obj);
#line 306 "request.c"
}

static GType
repose_models_request_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReposeModelsRequestClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repose_models_request_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReposeModelsRequest), 0, (GInstanceInitFunc) repose_models_request_instance_init, NULL };
	GType repose_models_request_type_id;
	repose_models_request_type_id = g_type_register_static (G_TYPE_OBJECT, "ReposeModelsRequest", &g_define_type_info, 0);
	ReposeModelsRequest_private_offset = g_type_add_instance_private (repose_models_request_type_id, sizeof (ReposeModelsRequestPrivate));
	return repose_models_request_type_id;
}

GType
repose_models_request_get_type (void)
{
	static volatile gsize repose_models_request_type_id__volatile = 0;
	if (g_once_init_enter (&repose_models_request_type_id__volatile)) {
		GType repose_models_request_type_id;
		repose_models_request_type_id = repose_models_request_get_type_once ();
		g_once_init_leave (&repose_models_request_type_id__volatile, repose_models_request_type_id);
	}
	return repose_models_request_type_id__volatile;
}

static void
_vala_repose_models_request_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec)
{
	ReposeModelsRequest * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest);
#line 20 "../src/model/request.vala"
	switch (property_id) {
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_NAME_PROPERTY:
#line 20 "../src/model/request.vala"
		g_value_set_string (value, repose_models_request_get_name (self));
#line 20 "../src/model/request.vala"
		break;
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_URL_PROPERTY:
#line 20 "../src/model/request.vala"
		g_value_set_string (value, repose_models_request_get_url (self));
#line 20 "../src/model/request.vala"
		break;
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_METHOD_PROPERTY:
#line 20 "../src/model/request.vala"
		g_value_set_string (value, repose_models_request_get_method (self));
#line 20 "../src/model/request.vala"
		break;
#line 359 "request.c"
		default:
#line 20 "../src/model/request.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/model/request.vala"
		break;
#line 365 "request.c"
	}
}

static void
_vala_repose_models_request_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec)
{
	ReposeModelsRequest * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest);
#line 20 "../src/model/request.vala"
	switch (property_id) {
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_NAME_PROPERTY:
#line 20 "../src/model/request.vala"
		repose_models_request_set_name (self, g_value_get_string (value));
#line 20 "../src/model/request.vala"
		break;
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_URL_PROPERTY:
#line 20 "../src/model/request.vala"
		repose_models_request_set_url (self, g_value_get_string (value));
#line 20 "../src/model/request.vala"
		break;
#line 20 "../src/model/request.vala"
		case REPOSE_MODELS_REQUEST_METHOD_PROPERTY:
#line 20 "../src/model/request.vala"
		repose_models_request_set_method (self, g_value_get_string (value));
#line 20 "../src/model/request.vala"
		break;
#line 397 "request.c"
		default:
#line 20 "../src/model/request.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/model/request.vala"
		break;
#line 403 "request.c"
	}
}

