/* root_state.c generated by valac 0.48.14, the Vala compiler
 * generated from root_state.vala, do not modify */

/* root_state.vala
 *
 * Copyright 2021 Benjamin Quinn
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib.h>

#define REPOSE_MODELS_TYPE_ROOT_STATE (repose_models_root_state_get_type ())
#define REPOSE_MODELS_ROOT_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootState))
#define REPOSE_MODELS_ROOT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootStateClass))
#define REPOSE_MODELS_IS_ROOT_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_MODELS_TYPE_ROOT_STATE))
#define REPOSE_MODELS_IS_ROOT_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_MODELS_TYPE_ROOT_STATE))
#define REPOSE_MODELS_ROOT_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootStateClass))

typedef struct _ReposeModelsRootState ReposeModelsRootState;
typedef struct _ReposeModelsRootStateClass ReposeModelsRootStateClass;
typedef struct _ReposeModelsRootStatePrivate ReposeModelsRootStatePrivate;

#define REPOSE_MODELS_TYPE_REQUEST (repose_models_request_get_type ())
#define REPOSE_MODELS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequest))
#define REPOSE_MODELS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))
#define REPOSE_MODELS_IS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_IS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), REPOSE_MODELS_TYPE_REQUEST))
#define REPOSE_MODELS_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), REPOSE_MODELS_TYPE_REQUEST, ReposeModelsRequestClass))

typedef struct _ReposeModelsRequest ReposeModelsRequest;
typedef struct _ReposeModelsRequestClass ReposeModelsRequestClass;
enum  {
	REPOSE_MODELS_ROOT_STATE_0_PROPERTY,
	REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY,
	REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUESTS_PROPERTY,
	REPOSE_MODELS_ROOT_STATE_NUM_PROPERTIES
};
static GParamSpec* repose_models_root_state_properties[REPOSE_MODELS_ROOT_STATE_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _ReposeModelsRootState {
	GObject parent_instance;
	ReposeModelsRootStatePrivate * priv;
};

struct _ReposeModelsRootStateClass {
	GObjectClass parent_class;
};

struct _ReposeModelsRootStatePrivate {
	ReposeModelsRequest* _active_request;
	GtkListStore* _active_requests;
};

static gint ReposeModelsRootState_private_offset;
static gpointer repose_models_root_state_parent_class = NULL;

GType repose_models_root_state_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeModelsRootState, g_object_unref)
GType repose_models_request_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ReposeModelsRequest, g_object_unref)
ReposeModelsRootState* repose_models_root_state_new (void);
ReposeModelsRootState* repose_models_root_state_construct (GType object_type);
ReposeModelsRequest* repose_models_root_state_get_active_request (ReposeModelsRootState* self);
void repose_models_root_state_set_active_request (ReposeModelsRootState* self,
                                                  ReposeModelsRequest* value);
GtkListStore* repose_models_root_state_get_active_requests (ReposeModelsRootState* self);
static void repose_models_root_state_finalize (GObject * obj);
static GType repose_models_root_state_get_type_once (void);
static void _vala_repose_models_root_state_get_property (GObject * object,
                                                  guint property_id,
                                                  GValue * value,
                                                  GParamSpec * pspec);
static void _vala_repose_models_root_state_set_property (GObject * object,
                                                  guint property_id,
                                                  const GValue * value,
                                                  GParamSpec * pspec);

static inline gpointer
repose_models_root_state_get_instance_private (ReposeModelsRootState* self)
{
	return G_STRUCT_MEMBER_P (self, ReposeModelsRootState_private_offset);
}

ReposeModelsRootState*
repose_models_root_state_construct (GType object_type)
{
	ReposeModelsRootState * self = NULL;
#line 20 "../src/model/root_state.vala"
	self = (ReposeModelsRootState*) g_object_new (object_type, NULL);
#line 20 "../src/model/root_state.vala"
	return self;
#line 108 "root_state.c"
}

ReposeModelsRootState*
repose_models_root_state_new (void)
{
#line 20 "../src/model/root_state.vala"
	return repose_models_root_state_construct (REPOSE_MODELS_TYPE_ROOT_STATE);
#line 116 "root_state.c"
}

ReposeModelsRequest*
repose_models_root_state_get_active_request (ReposeModelsRootState* self)
{
	ReposeModelsRequest* result;
	ReposeModelsRequest* _tmp0_;
#line 21 "../src/model/root_state.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 21 "../src/model/root_state.vala"
	_tmp0_ = self->priv->_active_request;
#line 21 "../src/model/root_state.vala"
	result = _tmp0_;
#line 21 "../src/model/root_state.vala"
	return result;
#line 132 "root_state.c"
}

static gpointer
_g_object_ref0 (gpointer self)
{
#line 21 "../src/model/root_state.vala"
	return self ? g_object_ref (self) : NULL;
#line 140 "root_state.c"
}

void
repose_models_root_state_set_active_request (ReposeModelsRootState* self,
                                             ReposeModelsRequest* value)
{
	ReposeModelsRequest* old_value;
#line 21 "../src/model/root_state.vala"
	g_return_if_fail (self != NULL);
#line 21 "../src/model/root_state.vala"
	old_value = repose_models_root_state_get_active_request (self);
#line 21 "../src/model/root_state.vala"
	if (old_value != value) {
#line 154 "root_state.c"
		ReposeModelsRequest* _tmp0_;
#line 21 "../src/model/root_state.vala"
		_tmp0_ = _g_object_ref0 (value);
#line 21 "../src/model/root_state.vala"
		_g_object_unref0 (self->priv->_active_request);
#line 21 "../src/model/root_state.vala"
		self->priv->_active_request = _tmp0_;
#line 21 "../src/model/root_state.vala"
		g_object_notify_by_pspec ((GObject *) self, repose_models_root_state_properties[REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY]);
#line 164 "root_state.c"
	}
}

GtkListStore*
repose_models_root_state_get_active_requests (ReposeModelsRootState* self)
{
	GtkListStore* result;
	GtkListStore* _tmp0_;
#line 22 "../src/model/root_state.vala"
	g_return_val_if_fail (self != NULL, NULL);
#line 22 "../src/model/root_state.vala"
	_tmp0_ = self->priv->_active_requests;
#line 22 "../src/model/root_state.vala"
	result = _tmp0_;
#line 22 "../src/model/root_state.vala"
	return result;
#line 181 "root_state.c"
}

static void
repose_models_root_state_class_init (ReposeModelsRootStateClass * klass,
                                     gpointer klass_data)
{
#line 20 "../src/model/root_state.vala"
	repose_models_root_state_parent_class = g_type_class_peek_parent (klass);
#line 20 "../src/model/root_state.vala"
	g_type_class_adjust_private_offset (klass, &ReposeModelsRootState_private_offset);
#line 20 "../src/model/root_state.vala"
	G_OBJECT_CLASS (klass)->get_property = _vala_repose_models_root_state_get_property;
#line 20 "../src/model/root_state.vala"
	G_OBJECT_CLASS (klass)->set_property = _vala_repose_models_root_state_set_property;
#line 20 "../src/model/root_state.vala"
	G_OBJECT_CLASS (klass)->finalize = repose_models_root_state_finalize;
#line 20 "../src/model/root_state.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY, repose_models_root_state_properties[REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY] = g_param_spec_object ("active-request", "active-request", "active-request", REPOSE_MODELS_TYPE_REQUEST, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
#line 20 "../src/model/root_state.vala"
	g_object_class_install_property (G_OBJECT_CLASS (klass), REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUESTS_PROPERTY, repose_models_root_state_properties[REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUESTS_PROPERTY] = g_param_spec_object ("active-requests", "active-requests", "active-requests", gtk_list_store_get_type (), G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
#line 202 "root_state.c"
}

static void
repose_models_root_state_instance_init (ReposeModelsRootState * self,
                                        gpointer klass)
{
#line 20 "../src/model/root_state.vala"
	self->priv = repose_models_root_state_get_instance_private (self);
#line 211 "root_state.c"
}

static void
repose_models_root_state_finalize (GObject * obj)
{
	ReposeModelsRootState * self;
#line 20 "../src/model/root_state.vala"
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootState);
#line 21 "../src/model/root_state.vala"
	_g_object_unref0 (self->priv->_active_request);
#line 22 "../src/model/root_state.vala"
	_g_object_unref0 (self->priv->_active_requests);
#line 20 "../src/model/root_state.vala"
	G_OBJECT_CLASS (repose_models_root_state_parent_class)->finalize (obj);
#line 226 "root_state.c"
}

static GType
repose_models_root_state_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ReposeModelsRootStateClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) repose_models_root_state_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ReposeModelsRootState), 0, (GInstanceInitFunc) repose_models_root_state_instance_init, NULL };
	GType repose_models_root_state_type_id;
	repose_models_root_state_type_id = g_type_register_static (G_TYPE_OBJECT, "ReposeModelsRootState", &g_define_type_info, 0);
	ReposeModelsRootState_private_offset = g_type_add_instance_private (repose_models_root_state_type_id, sizeof (ReposeModelsRootStatePrivate));
	return repose_models_root_state_type_id;
}

GType
repose_models_root_state_get_type (void)
{
	static volatile gsize repose_models_root_state_type_id__volatile = 0;
	if (g_once_init_enter (&repose_models_root_state_type_id__volatile)) {
		GType repose_models_root_state_type_id;
		repose_models_root_state_type_id = repose_models_root_state_get_type_once ();
		g_once_init_leave (&repose_models_root_state_type_id__volatile, repose_models_root_state_type_id);
	}
	return repose_models_root_state_type_id__volatile;
}

static void
_vala_repose_models_root_state_get_property (GObject * object,
                                             guint property_id,
                                             GValue * value,
                                             GParamSpec * pspec)
{
	ReposeModelsRootState * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootState);
#line 20 "../src/model/root_state.vala"
	switch (property_id) {
#line 20 "../src/model/root_state.vala"
		case REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY:
#line 20 "../src/model/root_state.vala"
		g_value_set_object (value, repose_models_root_state_get_active_request (self));
#line 20 "../src/model/root_state.vala"
		break;
#line 20 "../src/model/root_state.vala"
		case REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUESTS_PROPERTY:
#line 20 "../src/model/root_state.vala"
		g_value_set_object (value, repose_models_root_state_get_active_requests (self));
#line 20 "../src/model/root_state.vala"
		break;
#line 273 "root_state.c"
		default:
#line 20 "../src/model/root_state.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/model/root_state.vala"
		break;
#line 279 "root_state.c"
	}
}

static void
_vala_repose_models_root_state_set_property (GObject * object,
                                             guint property_id,
                                             const GValue * value,
                                             GParamSpec * pspec)
{
	ReposeModelsRootState * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, REPOSE_MODELS_TYPE_ROOT_STATE, ReposeModelsRootState);
#line 20 "../src/model/root_state.vala"
	switch (property_id) {
#line 20 "../src/model/root_state.vala"
		case REPOSE_MODELS_ROOT_STATE_ACTIVE_REQUEST_PROPERTY:
#line 20 "../src/model/root_state.vala"
		repose_models_root_state_set_active_request (self, g_value_get_object (value));
#line 20 "../src/model/root_state.vala"
		break;
#line 299 "root_state.c"
		default:
#line 20 "../src/model/root_state.vala"
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
#line 20 "../src/model/root_state.vala"
		break;
#line 305 "root_state.c"
	}
}

